---
- name: install jenkins
  hosts: localhost
  become: yes
  become_user: root
  vars: 
     mysqlhost: ""

  tasks:
   - name: Install add-apt-repostory
     become: yes
     apt:
       update_cache: yes
       name: software-properties-common 
       state: latest

   - name: Install Oracle Java 8
     become: yes
     apt: 
      update_cache: yes
      cache_valid_time: 3600
      name: openjdk-8-jdk
      state: latest
    

   - name: Install key for the Jenkins apt repository
     apt_key:
       url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
       state: present

   - name: Install access to the Jenkins apt repository
     apt_repository:
       repo: deb http://pkg.jenkins.io/debian-stable binary/
       state: present
       filename: 'jenkins'

   - name: Install Jenkins package
     become: yes
     apt:
         update_cache: yes
         name: jenkins
         state: present 
  
   - name: Change Jenkins JAVA options
     lineinfile: 
       dest: /var/lib/jenkins/config.xml
       regexp: <useSecurity>true</useSecurity>
       line: <useSecurity>false</useSecurity>
       state: present

   - name: Start Jenkins service and enable on boot
     service:
       name: jenkins
       state: restarted
       enabled: yes 
    
   - name: Wait for Jenkins to restart
     wait_for:
       host: localhost
       port: 8080
       delay: 30
       timeout: 300
   
   
   - name: install recommanede plugins
     jenkins_plugin:
       name: "{{ item }}" 
     with_items:
       - git
       - template-project
       - pipeline
       - docker-workflow
       - template-project
       - config-file-provider
       - bitbucket
       - git
       - pipeline-stage-view
       - pipeline-utility-steps
       - workflow-aggregator
       - pipeline-github
       - ssh-agent
       - ssh-slaves
       
   - name: Start Jenkins service and enable on boot
     service:
       name: jenkins
       state: restarted
       enabled: yes    

   - name: Wait for Jenkins to restart
     wait_for:
       host: localhost
       port: 8080
       delay: 60
       timeout: 300 

  
   - name: add environment variables
     become: yes
     jenkins_script: 
        script:  "{{ lookup('file', 'templates/global-env-vars.groovy') }}"
        validate_certs: no
        args:
         mysqlhost: "{{ mysqlhost }}"         


       

  