---

apiVersion: v1     
kind: Service
metadata:
  name: appsvc
  labels:
    app: flask
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8181
  selector:
    app: flask

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: michalazarovitz/midproj
        ports:
        - containerPort: 8181
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
                name: mysqlconfig
                key: MYSQL_HOST    
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
                name: mysqlconfig
                key: MYSQL_USER
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
               name: db-pass
               key: MYSQL_PWD
    