global:
  enabled: false
  domain: consul
  image: "consul:1.4.0"
  imageK8S: "hashicorp/consul-k8s:0.8.1"
  datacenter: opsschool
  enablePodSecurityPolicies: false
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key
  bootstrapACLs: false

server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: 3 # Should <= replicas count
  enterpriseLicense:
    secretName: null
    secretKey: null
  storage: 10Gi
  storageClass: null
  connect: true
  resources: null
  updatePartition: 0
  disruptionBudget:
    enabled: true
    maxUnavailable: null
  extraConfig: |
    {}
  extraVolumes: []
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname
  tolerations: ""
  nodeSelector: null
  priorityClassName: ""
  annotations: null
  extraEnvironmentVars: {}

  
client:
  enabled: true
  image: null
  join: 
    - "provider=aws tag_key=consul_server tag_value=true"
  grpc: false
  exposeGossipPorts: true
  resources: null
  extraConfig: |
    {}
  extraVolumes: []
  tolerations: ""
  nodeSelector: null
  priorityClassName: ""
  annotations: null
  extraEnvironmentVars: {}
    

dns:
  enabled: true

ui:
  enabled: "-"
  service:
    enabled: true
    type: null
    annotations: null
    additionalSpec: null

syncCatalog:
  enabled: true
  image: null
  default: true 
  toConsul: true
  toK8S: true
  k8sPrefix: null
  consulPrefix: null
  k8sTag: null
  syncClusterIPServices: true
  nodePortSyncType: ExternalFirst
  aclSyncToken:
    secretName: null
    secretKey: null
  nodeSelector: null


connectInject:
  enabled: false
  image: null # image for consul-k8s that contains the injector
  default: false # true will inject by default, otherwise requires annotation
  imageConsul: null
  imageEnvoy: null
  namespaceSelector: null
  certs:
    secretName: null
    caBundle: ""
    certName: tls.crt
    keyName: tls.key

  nodeSelector: null
  aclBindingRuleSelector: "serviceaccount.name!=default"

 
  centralConfig:
    enabled: false
    defaultProtocol: null
    proxyDefaults: |
      {}
